# Generated by Django 2.2.8 on 2019-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица, № Дома')),
            ],
            options={
                'verbose_name': 'Населенные пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.CreateModel(
            name='ClientLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='ClientPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='executorlegal',
            options={'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.AlterModelOptions(
            name='executorperson',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AddField(
            model_name='driver',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A1', 'A1'), ('B', 'B'), ('B1', 'B1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('BE', 'BE'), ('CE', 'CE'), ('C1E', 'C1E'), ('DE', 'DE'), ('D1E', 'D1E'), ('M', 'M'), ('Tm', 'Tm'), ('Tb', 'Tb')], default=None, max_length=4, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
