# Generated by Django 2.2.8 on 2019-12-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191218_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'На согласовании'), (2, 'В работе'), (3, 'Выполнен'), (3, 'Отказ клиента')], default=1)),
                ('address_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderClientEnd', to='info.Address', verbose_name='Дата разгрузки')),
                ('address_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderClientStart', to='info.Address', verbose_name='Дата погрузки')),
                ('client_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ClientLegal', verbose_name='Клиент')),
                ('client_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ClientPerson', verbose_name='Клиент')),
                ('drivers', models.ManyToManyField(blank=True, to='info.Driver', verbose_name='Водители')),
                ('executor_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ExecutorLegal', verbose_name='Исполнитель')),
                ('executor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.ExecutorPerson', verbose_name='Исполнитель')),
                ('goods', models.ManyToManyField(blank=True, to='info.Goods', verbose_name='Товары')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Organization', verbose_name='Тариф')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Tariff', verbose_name='Тариф')),
                ('transports', models.ManyToManyField(blank=True, to='info.Transport', verbose_name='Транспортные средства')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
            },
        ),
    ]
