# Generated by Django 2.2.8 on 2020-01-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_orderclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='address_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderClientEnd', to='info.Address', verbose_name='Адрес разгрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='address_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderClientStart', to='info.Address', verbose_name='Адрес погрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='date',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разгрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='state',
            field=models.IntegerField(choices=[(1, 'На согласовании'), (2, 'В работе'), (3, 'Выполнен'), (3, 'Отказ клиента')], default=1, verbose_name='Состояние заказа'),
        ),
    ]
