# Generated by Django 2.2.8 on 2020-01-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200102_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderclient',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='transports',
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='address_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_client_end', to='info.Address', verbose_name='Адрес разгрузки'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='address_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_client_start', to='info.Address', verbose_name='Адрес погрузки'),
        ),
        migrations.CreateModel(
            name='TransportFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers', models.ManyToManyField(blank=True, to='info.Driver', verbose_name='Водители')),
                ('order_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_client_transport_full', to='info.Transport', verbose_name='Заказ клиента')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Transport', verbose_name='Транспортные средства')),
            ],
            options={
                'verbose_name': 'Загружженый автомобиль',
                'verbose_name_plural': 'Загруженные автомобили',
            },
        ),
        migrations.CreateModel(
            name='GoodsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('measure', models.IntegerField(choices=[(1, 'шт.'), (2, 'кг.'), (3, 'т.')], default=1, verbose_name='Еденица измерения')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TransportFull', verbose_name='Товар')),
                ('transport_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_full_goods_count', to='info.TransportFull', verbose_name='Загруженный транспорт')),
            ],
            options={
                'verbose_name': 'Колличество товара',
                'verbose_name_plural': 'Колличество товаров',
            },
        ),
    ]
