# Generated by Django 2.2.8 on 2020-01-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200103_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscount',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='goodscount',
            name='transport_full',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.TransportFull', verbose_name='Загруженный транспорт'),
        ),
        migrations.AlterField(
            model_name='transportfull',
            name='order_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.OrderClient', verbose_name='Заказ клиента'),
        ),
    ]
