# Generated by Django 2.2.8 on 2020-01-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20200110_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=100, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
            },
        ),
        migrations.RemoveField(
            model_name='clientlegal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clientlegal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clientperson',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clientperson',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='executorlegal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='executorperson',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='client_legal',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='client_person',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='executor_legal',
        ),
        migrations.RemoveField(
            model_name='orderclient',
            name='executor_person',
        ),
        migrations.AddField(
            model_name='clientlegal',
            name='client_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientperson',
            name='client_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executorlegal',
            name='executor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Executor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executorperson',
            name='executor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.Executor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='orderclient',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Executor', verbose_name='Исполнитель'),
        ),
    ]
