# Generated by Django 2.2.8 on 2020-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20200115_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
