# Generated by Django 2.2.8 on 2020-01-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20200115_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
    ]
