# Generated by Django 2.2.8 on 2020-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='number',
            field=models.CharField(default='', max_length=10, verbose_name='Номер'),
        ),
    ]
